config/routes.rb
Spina::Checkout::Engine.routes.draw do
  resources :order_items, only: [:destroy, :update]

  resources :checkout, path: '/' do
    collection do
      post :cancel_and_duplicate
    end
  end

end

app/models/spina/checkout/application_record.rb
module Spina
  module Checkout
    class ApplicationRecord < ActiveRecord::Base
      self.abstract_class = true
    end
  end
end

app/controllers/spina/checkout/application_controller.rb
module Spina
  module Checkout
    class ApplicationController < ActionController::Base
      protect_from_forgery with: :exception

      include Shop::CurrentOrder
    end
  end
end

app/controllers/spina/checkout/checkout_controller.rb
module Spina::Checkout
  class CheckoutController < ApplicationController
    layout 'spina/checkout/application'

    helper Spina::Checkout::ApplicationHelper
    
    include Wicked::Wizard

    steps :shopping_cart, :details, :delivery, :payment, :overview, :success

    def show
      case step
      when :overview
        @order = current_order
        redirect_to wizard_path(:shopping_cart) and return unless @order.everything_valid?
      when :success
        # @order = Spina::Shop::Order.find_by(id: session[:order_id])
        # redirect_to wizard_path(:shopping_cart) and return if @order.blank? || @order.building?

        # If the order failed, duplicate it and try again.
        # Otherwise clear the session and show the success page.
        # Payment could still be pending, communicate accordingly.
        # if @order.failed? || @order.cancelled?
        #   session[:order_id] = @order.duplicate.try(:id)
        #   flash[:error] = t("spina.checkout.payment_failed_try_again")
        #   redirect_to wizard_path(:overview) and return
        # else
        #   session[:order_id] = nil
        # end
      else
        @order = current_order
        redirect_to wizard_path(:overview) and return unless @order.building?
      end
      render_wizard
    end

    def update
      @order = current_order

      case step
      when :shopping_cart
        @order.validate_stock = true
      when :details
        @order.validate_details = true
      when :delivery
        @order.validate_delivery = true
      when :payment
        @order.validate_payment = true
      when :overview
        # Confirm order!
        @order.transition_to(:confirming, user: @order.billing_name, ip_address: request.remote_ip)

        if @order.confirming?
          if @order.nothing_owed?
            @order.transition_to(:received, user: @order.billing_name, ip_address: request.remote_ip)
            @order.transition_to(:paid, user: @order.billing_name, ip_address: request.remote_ip)
            redirect_to checkout_path('success', locale: I18n.locale) and return
          else
            redirect_to @order.payment_url and return
          end
        else
          redirect_to checkout_path('shopping_cart', locale: I18n.locale) and return
        end
      end

      @order.update_attributes(order_params) if params[:order].present?
      render_wizard @order
    rescue ActiveRecord::RecordInvalid
      redirect_to checkout_path('shopping_cart', locale: I18n.locale)
    end

    def cancel_and_duplicate
      @order = current_order
      @order.transition_to!(:cancelled, user: @order.billing_name, ip_address: request.remote_ip)
      session[:order_id] = @order.duplicate.try(:id)
      redirect_to wizard_path(:shopping_cart)
    end

    private

      def order_params
        params.require(:order).permit(:company, :email, :phone, :first_name, :last_name, :billing_country_id, :billing_street1, :billing_city, :billing_house_number, :billing_house_number_addition, :billing_postal_code, :separate_delivery_address, :delivery_name, :delivery_country_id, :delivery_postal_code, :delivery_street1, :delivery_city, :delivery_house_number, :delivery_house_number_addition, :delivery_option_id, :payment_method, :reference, order_items_attributes: [:quantity, :id])
      end

  end
end

app/controllers/spina/checkout/order_items_controller.rb
module Spina::Checkout
  class OrderItemsController < ApplicationController

    before_action :set_order
    before_action :raise_exception_if_order_is_not_building

    def destroy
      @order_item = @order.order_items.find(params[:id])
      @order_item.destroy
      redirect_to checkout_path('shopping_cart', locale: I18n.locale)
    end

    private

      def set_order
        @order = current_order
      end

      def raise_exception_if_order_is_not_building
        raise Spina::Shop::Errors::OlderAlreadyReceived unless @order.building?
      end

  end
end

app/helpers/spina/checkout/application_helper.rb
module Spina
  module Checkout
    module ApplicationHelper

      def countries_for_select
        if current_customer.try(:country)
          @countries_for_select = [[current_customer.country.name, current_customer.country.id]]
        else
          @countries_for_select = Spina::Shop::Country.order(:name).map { |country| [country.name, country.id] }
        end
      end

      def payment_options_for_order(order)
        payment_options = %w(ideal sofort bancontact)
        payment_options
      end

    end
  end
end

app/views/layouts/spina/checkout/application.html.haml
!!!
%html
  %head
    %title Checkout
    = stylesheet_link_tag    'spina/checkout/application', 'data-turbolinks-track' => true
    = javascript_include_tag 'spina/checkout/application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0, user-scalable=0'}
    %meta{name: 'turbolinks-cache-control', content: 'no-cache'}
  %body
    %header#header
      = link_to '/', {data: {turbolinks: false}} do
        = image_tag 'spina/checkout/logo.jpg', width: "50%"

    %section#wizard_steps
      - wizard_steps.first(wizard_steps.size - 1).each_with_index do |step, index|
        - if past_step?(step) && (@step != :success)
          = link_to wizard_path(step), class: 'wizard-step' do
            .wizard-icon= index + 1
            %span=t "spina.checkout.steps.#{step}"
        - else
          .wizard-step{class: ('active' if step == @step)}
            .wizard-icon= index + 1
            %span=t "spina.checkout.steps.#{step}"

    = yield

app/views/spina/checkout/checkout/_sidebar.html.haml
.sidebar-container
  %table.table.table-sidebar-totals
    - if @step != :shopping_cart
      - @order.order_items.roots.each do |order_item|
        %tr
          %td{width: 50}
            .order-item-preview-image{data: {quantity: order_item.quantity}}
              - if order_item.orderable.product_images.first&.file&.attached?
                = image_tag main_app.url_for(order_item.orderable.product_images.first.file.variant(resize: '100x100')), width: 50
              - else
                = image_tag "http://placehold.it/100x100.png", width: 50

          %td
            .order-item-description= order_item.description
          %td.text-right.sidebar-price
            = number_to_currency order_item.total

        - order_item.children.each do |child|
          %tr.table-sidebar-addons
            %td
            %td
              = child.description
            %td.text-right
              - if child.total > 0
                +
                = number_to_currency child.total

    %tr
      %td{colspan: 3}
    %tr
      %td{colspan: 2}= Spina::Shop::Order.human_attribute_name :sub_total
      %td.text-right.sidebar-price= number_to_currency @order.order_total

    - if @order.requires_shipping?
      %tr
        %td{colspan: 2} Verzending
        %td.text-right.sidebar-price= number_to_currency @order.delivery_price

    %tr
      %td{colspan: 3}

    - if @order.vat_reverse_charge?
      %tr.text-muted
        %td{colspan: 2}=t 'spina.shop.tax.vat_reverse_charge'
        %td.text-right= number_to_currency BigDecimal.new(0)
    - else
      %tr.text-muted
        %td{colspan: 2}= Spina::Shop::Order.human_attribute_name :total_excluding_tax
        %td.text-right= number_to_currency @order.total_excluding_tax

      - @order.tax_amount_by_rates.each do |tax_rate|
        - unless tax_rate[0] == 0
          %tr
            %td.text-muted{colspan: 2}= "#{number_with_precision tax_rate[0], precision: 0}% btw"
            %td.text-right.text-muted= number_to_currency tax_rate[1][:tax_amount]

    %tr
      %td.sidebar-price-large{colspan: 2}= Spina::Shop::Order.human_attribute_name :total
      %th.text-right.sidebar-price-large= number_to_currency @order.total

app/views/spina/checkout/checkout/delivery.html.haml
%section#main_content
  %section#main
    = form_with model: @order, url: wizard_path, method: :put do |f|
      = hidden_field_tag :locale, I18n.locale
      
      .main-container
        .checkout-heading=t 'spina.checkout.choose_delivery'

        .form-group
          .form-options
            - @order.delivery_options.each do |option|
              .form-option
                = f.radio_button :delivery_option_id, option.id, checked: true

                .form-option-container
                  .form-option-radio-button
                  .form-option-description
                    %strong
                      =t "spina.checkout.delivery_options.#{option.name}.name"
                    %small
                      =t "spina.checkout.delivery_options.#{option.name}.description"
                      - if option.price_for_order(@order) != BigDecimal.new(0)
                        %strong= number_to_currency option.price_for_order(@order), unit: '€'

      .main-container-links
        .main-container
          = link_to t("spina.checkout.back_to_#{@previous_step}"), checkout_path(@previous_step, locale: I18n.locale), class: 'button button-link', style: "padding-left: 0px"

          = button_tag t('spina.checkout.next'), type: :submit, class: 'button button-primary'

  %aside#sidebar= render 'sidebar'

app/views/spina/checkout/checkout/details.html.haml
%section#main_content
  %section#main
    = form_for @order, url: wizard_path, method: :put do |f|
      = hidden_field_tag :locale, I18n.locale
      
      .main-container
        .checkout-heading=t 'spina.checkout.steps.details'

        .form
          .form-group
            = f.text_field :email, placeholder: "Email", value: @order.email || current_customer.try(:email)

        .checkout-subheading= Spina::Shop::Order.human_attribute_name(:billing_address)

        - if flash[:info].present?
          .notification.notification-info
            .notification-message
              = flash[:info]

        .form
          - if current_customer_account
            .form-group
              .form-control= f.text_field :company, value: @order.company || current_customer.try(:company), placeholder: Spina::Shop::Order.human_attribute_name(:company), disabled: true

          .form-group
            .form-control= f.text_field :first_name, value: @order.first_name || current_customer.try(:first_name), placeholder: Spina::Shop::Order.human_attribute_name(:first_name)
            .form-control= f.text_field :last_name, value: @order.last_name || current_customer.try(:last_name), placeholder: Spina::Shop::Order.human_attribute_name(:last_name)

          .form-group
            .form-control.form-control-large= f.text_field :billing_street1, placeholder: Spina::Shop::Order.human_attribute_name(:billing_street1), value: @order.billing_street1 || current_customer.try(:billing_address).try(:street1)
            .form-control= f.text_field :billing_house_number, placeholder: Spina::Shop::Order.human_attribute_name(:billing_house_number), value: @order.billing_house_number || current_customer.try(:billing_address).try(:house_number)
            .form-control= f.text_field :billing_house_number_addition, placeholder: Spina::Shop::Order.human_attribute_name(:billing_house_number_addition), value: @order.billing_house_number_addition || current_customer.try(:billing_address).try(:house_number_addition)

          .form-group
            .form-control= f.text_field :billing_postal_code, placeholder: Spina::Shop::Order.human_attribute_name(:billing_postal_code), value: @order.billing_postal_code || current_customer.try(:billing_address).try(:postal_code)
            .form-control= f.text_field :billing_city, placeholder: Spina::Shop::Order.human_attribute_name(:billing_city), value: @order.billing_city || current_customer.try(:billing_address).try(:city)

          .form-group
            .form-control= f.text_field :phone, placeholder: Spina::Shop::Order.human_attribute_name(:phone), value: @order.phone || current_customer.try(:phone)
            .form-control
              .select-dropdown= f.select :billing_country_id, options_for_select(countries_for_select, f.object.billing_country_id || current_customer.try(:country).try(:id)), prompt: t('spina.checkout.choose_country')

        = f.check_box :separate_delivery_address, value: @order.separate_delivery_address, placeholder: Spina::Shop::Order.human_attribute_name(:separate_delivery_address)
        = f.label :separate_delivery_address, Spina::Shop::Order.human_attribute_name(:separate_delivery_address), class: 'label'

        .form.checkout-delivery-fields
          - if current_customer.present? && current_customer.addresses.delivery.any?
            .form-group
              .form-control
                .select-dropdown
                  %select.choose-delivery-address
                    %option= t('spina.checkout.new_address')
                    - current_customer.addresses.delivery.order(:postal_code).each do |address|
                      %option{data: {name: address.name, street1: address.street1, house_number: address.house_number, house_number_addition: address.house_number_addition, postal_code: address.postal_code, city: address.city, country_id: address.country_id}}
                        = [address.postal_code, address.city].join(', ')
                        = "(#{address.name})"

          .form-group
            .form-control= f.text_field :delivery_name, value: @order.delivery_name || current_customer.try(:name), placeholder: Spina::Shop::Order.human_attribute_name(:delivery_name)

          .form-group
            .form-control.form-control-large= f.text_field :delivery_street1, placeholder: Spina::Shop::Order.human_attribute_name(:delivery_street1), value: @order.delivery_street1
            .form-control= f.text_field :delivery_house_number, placeholder: Spina::Shop::Order.human_attribute_name(:delivery_house_number), value: @order.delivery_house_number
            .form-control= f.text_field :delivery_house_number_addition, placeholder: Spina::Shop::Order.human_attribute_name(:delivery_house_number_addition), value: @order.delivery_house_number_addition

          .form-group
            .form-control= f.text_field :delivery_postal_code, placeholder: Spina::Shop::Order.human_attribute_name(:delivery_postal_code), value: @order.delivery_postal_code
            .form-control= f.text_field :delivery_city, placeholder: Spina::Shop::Order.human_attribute_name(:delivery_city), value: @order.delivery_city

          .form-group
            .form-control
              .select-dropdown= f.select :delivery_country_id, options_for_select(countries_for_select, f.object.delivery_country_id || current_customer.try(:country_id)), prompt: t('spina.checkout.choose_country')

      .main-container-links
        .main-container
          = link_to t('spina.checkout.back_to_cart'), checkout_path('shopping_cart', locale: I18n.locale), class: 'button button-link', style: 'padding-left: 0px'
          = button_tag t("spina.checkout.next"), type: :submit, class: 'button button-primary'

  %aside#sidebar= render 'sidebar'

app/views/spina/checkout/checkout/overview.html.haml
%section#main_content
  %section#main
    = form_for @order, url: wizard_path, method: :put do |f|
      = hidden_field_tag :locale, I18n.locale

      .main-container
        .checkout-heading=t 'spina.checkout.overview'

        - if @order.confirming?
          .notification.notification-danger
            .notification-message
              =t 'spina.checkout.order_not_yet_received'
              = @order.current_state
              = link_to t('spina.checkout.edit_order'), cancel_and_duplicate_checkout_index_path({locale: I18n.locale}), class: '', data: {method: :post}

        - if flash[:info].present?
          .notification.notification-info
            .notification-message
              = flash[:info]

        .checkout-blocks
          .checkout-block
            .checkout-subheading{style: 'margin-top: 0'} 
              - if @order.requires_shipping?
                =t('spina.checkout.shipping')
              - else
                =t('spina.checkout.pickup')

            - if @order.requires_shipping?
              %table.table
                %tr
                  %td= @order.delivery_name
                %tr
                  %td= @order.delivery_address
                %tr
                  %td= "#{@order.delivery_postal_code}, #{@order.delivery_city} #{@order.delivery_country.code}"

              %hr.checkout-block-divider/

              =t 'spina.checkout.delivery_method'

              .checkout-block-summary
                %div=t "spina.checkout.delivery_options.#{@order.delivery_option.name}.name"

          .checkout-block
            .checkout-subheading{style: 'margin-top: 0'}=t 'spina.checkout.billing_address'

            %table.table
              %tr
                %td= @order.billing_name
              %tr
                %td= @order.billing_address
              %tr
                %td= "#{@order.billing_postal_code}, #{@order.billing_city} #{@order.billing_country.code}"

            - if @order.reference.present?
              %hr.checkout-block-divider/

              = Spina::Shop::Order.human_attribute_name(:reference)

              .checkout-block-summary
                %div= @order.reference

            %hr.checkout-block-divider/

            =t 'spina.checkout.payment_method'

            .checkout-block-summary
              %div
                = image_tag "spina/checkout/payment_options/#{@order.payment_method}.svg", height: 20, style: 'vertical-align: middle'
                =t "spina.checkout.payment_options.#{@order.payment_method}"

      .main-container-links
        .main-container
          - if @order.building?
            = link_to t('spina.checkout.back_to_payment'), checkout_path('payment', locale: I18n.locale), class: 'button button-link', style: 'padding-left: 0px'

            = button_tag t('spina.checkout.confirm_order'), type: :submit, class: 'button button-primary'
          - else
            = link_to t('spina.checkout.edit_order'), cancel_and_duplicate_checkout_index_path({locale: I18n.locale}), class: 'button button-link', style: 'padding-left: 0px', data: {method: :post}

            = link_to t('spina.checkout.confirm_order'), @order.payment_url, class: 'button button-primary'

  %aside#sidebar= render 'sidebar'

app/views/spina/checkout/checkout/payment.html.haml
%section#main_content
  %section#main
    = form_for @order, url: wizard_path, method: :put do |f|
      = hidden_field_tag :locale, I18n.locale
      
      .main-container
        .checkout-heading=t 'spina.checkout.choose_payment'

        .form-group
          .form-options
            - payment_options_for_order(@order).each do |option|
              .form-option
                %label
                  = radio_button_tag 'order[payment_method]', option, option == f.object.payment_method

                  .form-option-container
                    .form-option-radio-button
                    .form-option-image
                      = image_tag "spina/checkout/payment_options/#{option}.svg", width: 30
                    .form-option-description
                      %strong=t "spina.checkout.payment_options.#{option}"

        %p{style: 'margin-top: 30px'}
          %strong=t 'spina.checkout.reference'
          %small.text-muted=t 'spina.checkout.optional'
        .form-group
          = f.text_field :reference, placeholder: Spina::Shop::Order.human_attribute_name(:reference), value: @order.reference

      .main-container-links
        .main-container
          = link_to t('spina.checkout.back_to_delivery'), checkout_path('delivery', locale: I18n.locale), class: 'button button-link', style: 'padding-left: 0px'
          = button_tag t('spina.checkout.next'), type: :submit, class: 'button button-primary'

  %aside#sidebar= render 'sidebar'

app/views/spina/checkout/checkout/shopping_cart.html.haml
%section#main_content
  %section#main
    = form_with model: @order, url: wizard_path, method: :put do |f|
      = hidden_field_tag :locale, I18n.locale

      .main-container
        .checkout-heading=t 'spina.checkout.shopping_cart'

        - if @order.errors.any?
          = @order.errors.full_messages.inspect

        %table.table.table-shopping-cart
          = f.fields_for :order_items, f.object.order_items.roots.sort_by{|o|o.orderable.name} do |ff|
            %tr
              %td{style: 'width: 50px'}
                .order-item-preview-image
                  - if ff.object.orderable.product_images.first&.file&.attached?
                    = image_tag main_app.url_for(ff.object.orderable.product_images.first.file.variant(resize: '100x100')), width: 50
                  - else
                    = image_tag "http://placehold.it/100x100.png", width: 50

              %td 
                .order-item-description= ff.object.orderable.name
                %br/
                %small.text-muted= number_to_currency ff.object.unit_price, unit: '€'
              %td{width: 150, style: 'padding-right: 10px'}
                .order-item-quantity-control{data: {controller: "order-item-quantity-control"}}
                  = ff.hidden_field :quantity, data: {target: 'order-item-quantity-control.quantityField'}
                  = link_to '#', class: 'order-item-quantity-control-subtract', data: {action: 'order-item-quantity-control#subtract'} do
                    = image_tag 'spina/checkout/subtract.svg'
                  .order-item-quantity-control-number
                    %span{data: {target: 'order-item-quantity-control.number'}}= ff.object.quantity
                    &times;
                  = link_to '#', class: 'order-item-quantity-control-add', data: {action: 'order-item-quantity-control#add'} do
                    = image_tag 'spina/checkout/add.svg'

              %td{width: 40, style: 'padding-right: 0'}
                = link_to order_item_path(ff.object), class: 'order-item-delete', data: {method: :delete, confirm: t('spina.checkout.are_you_sure')} do
                  = image_tag 'spina/checkout/delete.svg'

              %th.text-right{width: 100}
                = number_to_currency ff.object.total

            - ff.object.children.each do |child|
              %tr.shopping-cart-addons
                %td
                %td{colspan: 3}
                  = child.description
                %td.text-right
                  - if child.total > 0
                    +
                    = number_to_currency child.total

      .main-container-links
        .main-container
          = link_to t('spina.checkout.back_to_website'), '/', class: 'button button-link', style: 'padding-left: 0px', data: {turbolinks: false}
          = button_tag t('spina.checkout.next'), type: :submit, class: 'button button-primary'

  %aside#sidebar= render 'sidebar'

app/views/spina/checkout/checkout/success.html.haml
%section#main_content
  %section#main
    .main-container
      .checkout-heading Bestelling bevestigd. Je ontvangt een email ter bevestiging.